name: Test and publish

on:
  push:
    tags:
      - release*
    branches-ignore:
      - '*'

jobs:
  test_publish:
    name: Test And AutoPublish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'http://npm.lkangle.cn'
      - name: Cache Node Modules
        id: cache_deps
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: steps.cache_deps.outputs.cache-hit != 'true'
        run: yarn install
      - name: Do Test
        run: sudo yarn test
      - name: Publish
        run: yarn publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LKL_NPM_TOKEN }}
